### ISSUE TITLE
Gluon use cases with Trilateral3 & linc_glfw

### ISSUE THREAD

**Issue by nanjizal** [haxiomic/gluon#12]
You can find some helpers I have created for use with Gluon, created with the help of haxeiomic. 
They are still under dev:
https://github.com/nanjizal/kitGL/tree/master/src/kitGL/gluon

Graphical examples some animated using Trilateral3 using a linc_glfw window ( mac terminal code online ).
https://github.com/TrilateralX/TrilateralSamples/tree/master/gluon/

Currently Trilateral3 is quite modular all repos on my github so likely not ideal to setup just yet, but if you do try and get stuck to let me know.

![AtriangleGluon](https://user-images.githubusercontent.com/20134338/86254215-69fac580-bbad-11ea-8d21-d52cf89c475d.png)
![BsvgpathGluon](https://user-images.githubusercontent.com/20134338/86254267-7b43d200-bbad-11ea-860f-58276ba2b950.png)
![Cfillgluon](https://user-images.githubusercontent.com/20134338/86254275-80a11c80-bbad-11ea-98b6-a690dfc977be.png)
![DecllipseGluon](https://user-images.githubusercontent.com/20134338/86254298-85fe6700-bbad-11ea-85ff-d57256344ab0.png)
![EregularColor](https://user-images.githubusercontent.com/20134338/86254311-8a2a8480-bbad-11ea-96a3-50c5893bfc98.png)
![ElinesGluon](https://user-images.githubusercontent.com/20134338/86254329-90206580-bbad-11ea-826c-c32b8e152e34.png)
![GrotateMoveGluon](https://user-images.githubusercontent.com/20134338/86254345-97477380-bbad-11ea-8251-20d3c0052ad6.png)

**Comment by haxiomic** [comment]
Hey @nanjizal, this is great :), do mind if I move it into a markdown file inside the repo and link to it from the README?

**Comment by haxiomic** [comment]
Here's what I mean: https://github.com/haxiomic/gluon/blob/master/EXAMPLES.md

**Comment by nanjizal** [comment]
Sure. 
Your original main class is here https://github.com/nanjizal/kitGL/blob/master/src/kitGL/gluon/Glwrapper.hx
I wrap it in a class that sets up generic interleave shader, you can feed that generically so it's not really tied to trilateral you just have to pass it XYZARGB data.
The api docs for kitGL are here.
https://nanjizal.github.io/kitGL/pages/kitGL/glWeb/InterleaveAlterGL.html
there are also api docs for dsHelper and trilateral3 and most of the other modules.

**Comment by nanjizal** [comment]
would love any further assistance on adding code for threads.
You will notice kitGL tries to set them up similar for Lime ( now working ) and NME, Heaps ( both compile but may not render ? ) , and WebGL ( working ).  I probably need some better naming InterleaveAlterGL and InterleaveDataGL are really rubbish names, but thought more important to get code working.

**Comment by nanjizal** [comment]
the idea is they dislocate the ugly GL stuff from drawing code.

**Comment by nanjizal** [comment]
kitGL does not have any direct dependancy really on trilateral3 it just a toolkit for assembling gl bits together.

**Comment by haxiomic** [comment]
I've not dug into your code but word of warning regarding adding threads: OpenGL doesn't support multithreading, so for your program to be stable all OpenGL commands must be executed on whichever thread hosts the opengl context (probably the main thread)

Typically multi-threading graphics programs run code on other threads to generate data and then synchronize with the main (OpenGL) thread to run the gl.* commands

WebGPU supports multi-threading and in the future when that gathers steam I will use it has my main haxe GPU API
