### ISSUE TITLE
Glow

### ISSUE THREAD

**Issue by nanjizal** [haxiomic/gluon#15]
Github was suggesting repos, Glow seemed interesting Rust one with similar intentions to Gluon but maybe not as extensive?  I don't know rust yet but maybe you will find some interesting ideas.
https://github.com/grovesNL/glow

by the way I never remember your github name spelling, and gluon seems very popular project name ( think there is even another project same name in haxelib ).  Suggest changing/varying name to something not as widely used - GaugeBoson ?

**Comment by haxiomic** [comment]
Glow looks great, thanks for the link

Yeah the name clash is annoying I agree, I should have published this to haxelib years ago :P

Gluon will hopefully one day get replaced by a different lib when I can finally get back to haxe projects – the plan is a lib that implements the basic web apis for hxcpp like WebGL, WebAudio etc. It exists, just not publically released

**Comment by haxiomic** [comment]
Just closing this as there's no action to take but thanks for the info :)
